art_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('product.urls', namespace='product')),
     path("__reload__/", include("django_browser_reload.urls")),
   
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from .views import (cart_add,cart_detail,cart_remove)

app_name='cart'

urlpatterns=[
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    
]

orders/urls.py
from django.urls import path

from .views import (order_create, admin_order_detail,admin_order_pdf)

app_name='orders'

urlpatterns=[
    path('create/', order_create, name='order_create'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/', admin_order_pdf, name='admin_order_pdf'),
]

product/urls.py
from django.urls import path
from .views import (product_list, product_detail,landing_page)

app_name='product'

urlpatterns=[
    path('',landing_page, name='landing' ),
    path('list/',product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('detail/<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES=[(i, str(i)) for i in range(1, 4)]

class CartAddProductForm(forms.Form):
    #quantity=forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,label='', coerce=int,widget=forms.Select(attrs={
        #'class':''
    # }))
     # Adding a field to track the action of adding to the cart
    add_to_cart = forms.BooleanField(initial=True, widget=forms.HiddenInput())
    override=forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput())
    

cart/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product
from .cart import Cart
from .forms import CartAddProductForm

def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    # Modify the form instantiation to include the initial data for add_to_cart
    form_data = {'add_to_cart': True}
    form = CartAddProductForm(request.POST or None, initial=form_data)

    if form.is_valid():
        cd = form.cleaned_data
        # You can handle the quantity logic here based on your use case
        # For example, you might always add one item per click
        cart.add(item=product, quantity=1, override_quantity=cd['override'])

    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart=Cart(request)
    product=get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart=Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity':item['quantity'],
            'override':True

        })
    return render(request, 'cart/detail.html',{'cart':cart})

def product_list(request):
    products=Product.objects.all()
    context={"products":products}
    return render(request, "cart/list.html", context)

templates/cart/detail.html
{% extends 'base.html' %}

{% block title %}
Your Shopping Cart
{% endblock %}
{% block content %}
<div class="min-h-full py-10 bg-gradient-to-br from-sky-800 to-gray-100 ">
    {% if cart.get_total_price > 0 %}
    <h2 class="mb-4 text-3xl font-semibold text-center text-white capitalize">your shopping cart</h2>
       <div class="mx-auto bg-white shadow-2xl md:w-2/5 rounded-2xl">
        {% for item in cart %}
        {% with product=item.product %}
              <div class="grid grid-cols-4 gap-3 px-6 py-4">
                <div class="col-span-1">
                    <img src="{{product.image.url }}" alt="{{product.name}}" class="w-20 h-20 rounded-lg">
                </div>
               <div class="col-span-2">
                <h3 class="mb-4 font-semibold text-md">{{product.name}}</h3>
                
                    
                    <div class="flex text-md ">
                        <button type="button" class="flex items-center space-x-1">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="w-4 h-4 fill-current">
                            <path d="M96,472a23.82,23.82,0,0,0,23.579,24H392.421A23.82,23.82,0,0,0,416,472V152H96Zm32-288H384V464H128Z"></path>
                            <rect width="32" height="200" x="168" y="216"></rect>
                            <rect width="32" height="200" x="240" y="216"></rect>
                            <rect width="32" height="200" x="312" y="216"></rect>
                            <path d="M328,88V40c0-13.458-9.488-24-21.6-24H205.6C193.488,16,184,26.542,184,40V88H64v32H448V88ZM216,48h80V88H216Z"></path>
                        </svg>
                        <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                            {% csrf_token %}
                            <input type="submit" value="Remove" class="cursor-pointer">
                        </form>
        
                        </button>
        
                        </div>

               </div>
                
                <div class="col-span-1">
                    <p class="text-lg font-semibold">$ {{item.price}}</p>
                </div>
              </div>
        <hr class="m-8 bg-gray-400">
        {% endwith %}
        {% endfor %}
        <div class="flex flex-col items-end justify-end gap-2 pb-6 pr-2">
            <div class="mb-4">
                <p>Total amount:
                    <span class="ml-6 text-2xl font-semibold">${{cart.get_total_price}}</span>
                </p>
                <p class="text-sm dark:text-gray-400">Not including taxes and shipping costs</p>
            </div>
            {% else %}
            {% include 'cart/list.html' %}
        {% endif %}
            <div class="">
                <a href="{% url 'product:product_list' %}" class="">
                    <button type="button" class="px-6 py-3 text-white bg-blue-500 rounded-md">Back
                        <span class="sr-only sm:not-sr-only">to shop</span>
                    </button>
                </a>
                 {% if cart.get_total_price > 0 %}
                <a href="{% url 'orders:order_create' %}" class="">
                    <button type="button" class="px-6 py-3 text-white bg-teal-600 rounded-lg">
                        <span class="sr-only sm:not-sr-only">Continue to</span>Checkout
                    </button>
                </a>
                {% endif %}
            </div>
        </div>
       </div>

</div>

{% endblock %}

templates/cart/list.html
{% if cart|length == 0 %}
    <div class="flex flex-wrap">
      {% for product in products %}
        <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
          <a href="{{ product.get_absolute_url }}" class="block relative h-48 rounded overflow-hidden">
            <img alt="{{ product.name }}" class="object-cover object-center w-full h-full block" src="{{ product.image.url }}">
          </a>
          <div class="mt-4">
            <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">{{ product.category }}</h3>
            <h2 class="text-gray-900 title-font text-lg font-medium">{{ product.name|title }}</h2>
            <p class="mt-1">${{ product.price }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  {% endif %}