art_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('product.urls', namespace='product')),
     path("__reload__/", include("django_browser_reload.urls")),
   
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from .views import (cart_add,cart_detail,cart_remove)

app_name='cart'

urlpatterns=[
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    
]

product/urls.py
from django.urls import path
from .views import (product_list, product_detail,landing_page)

app_name='product'

urlpatterns=[
    path('',landing_page, name='landing' ),
    path('list/',product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('detail/<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

product/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

class Category(models.Model):
    name=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering=['name']
        indexes=[
            models.Index(fields=['name']),
        ]
        verbose_name='Category'
        verbose_name_plural='Categories'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('product:product_list_by_category', args=[self.slug])


class ArtSize(models.Model):
    size=models.CharField(max_length=10)

    def __str__(self):
        return self.size


class Product(models.Model):
    AVAILABLE_SIZE=[
        ('SM','Small'),
        ('MD','Medium'),
        ('LG','Large'),
        ('XL','ExtraLarge'),
    ]
    category=models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name=models.CharField(max_length=200)
    slug=models.SlugField(max_length=200)
    image=models.ImageField(upload_to='products/%Y/%m/%d')
    image_1=models.ImageField(upload_to='products',blank=True, null=True)
    image_2=models.ImageField(upload_to='products',blank=True, null=True)
    image_3=models.ImageField(upload_to='products',blank=True, null=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    available=models.BooleanField(default=True)
    size=models.CharField(max_length=4, choices=AVAILABLE_SIZE)
    available_size=models.ForeignKey(ArtSize, on_delete=models.CASCADE)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=['name']
        indexes=[
            models.Index(fields=['id','slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),

        ]
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('product:product_detail', args=[self.id, self.slug])
    
    def save(self, *args, **kwargs):
        super().save(self, *args,**kwargs)
        self.slug=slugify(self.name)
    

product/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product,Category
from cart.forms import CartAddProductForm
from .filters import ProductFilter

def landing_page(request):
    products=Product.objects.all().order_by('-created')[:5]
    categories=Category.objects.all()[:4]
    cart_product_form=CartAddProductForm()
    context={'products':products,'categories':categories,'form':cart_product_form}
    return render(request, 'product/landing.html',context)

def product_list(request, category_slug=None):
    category=None
    categories=Category.objects.all()
    products=Product.objects.all()
    if category_slug:
        category=get_object_or_404(Category, slug=category_slug)
        products=products.filter(category=category)
    products_filtered=ProductFilter(request.GET, queryset=products).qs
    context={'categories':categories, 'products':products,'category':category,'products_filtered':products_filtered}
    return render(request, 'product/product_list.html', context)


def product_detail(request,id, slug):
    product=get_object_or_404(Product, available=True, id=id, slug=slug)
    related_products=Product.objects.filter(category=product.category).exclude(id=id)[:3]
    cart_product_form=CartAddProductForm()
    context={'product':product, 'related_products':related_products,'form':cart_product_form}
    return render(request, 'product/product_detail.html', context)

templates/product/landing.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock %}

{% block content %}
<style>

 

    /* swiper-container {
      width: 100%;
      height: 100%;
    } */

    /* swiper-slide {
      text-align: center;
      font-size: 18px;
      background: #fff;
      display: flex;
      justify-content: center;
      align-items: center;
    } */

    swiper-slide img {
      display: block;
      object-fit: cover;
    }
  </style>
<div class="min-h-">
    <swiper-container class="mySwiper" pagination="true" pagination-clickable="true" navigation="true" space-between="30"
    centered-slides="true" autoplay-delay="7500" autoplay-disable-on-interaction="false">
    <swiper-slide>
        <div class="slide-content relative">
            <h2 class="absolute top-[50%] text-white bottom-[50%]  text-4xl right-[42%]">Heading 1</h2>
            <img src="{% static 'image/img1.png' %}" alt="" class="h-[600px] w-full">
          </div>
    </swiper-slide>
    <swiper-slide>
        <img src="{% static 'image/img2.jpg' %}" alt="" class="h-[600px] w-full">
    </swiper-slide>
    <swiper-slide>
        <img src="{% static 'image/img3.jpg' %}" alt="" class="h-[600px] w-full">
    </swiper-slide>
  </swiper-container>

  <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>


</div>
<div class="my-10 mx-10 grid md:grid-cols-3 grid-cols-1 gap-4 ">
    <div class="px-10 py-5 rounded-lg border-2 border-lime-600 flex flex-col items-center justify-center">
         <div class="">
            <i class="fa-solid fa-truck text-6xl text-lime-700"></i>
         </div>  
        <p class="text-md text-lime-600">
            Free Shipping
        </p>
      
    </div>
    <div  class="px-10 py-5 rounded-lg border-2 border-lime-600 flex flex-col items-center justify-center">
           <div class="">
            <i class="fa-solid fa-credit-card text-6xl text-lime-700"></i>
           </div>
        <p class="text-md text-lime-600">
            Secure payment 
        </p>
      
    </div>
    <div class="px-10 py-5 rounded-lg border-2 border-lime-600 flex flex-col items-center justify-center">
         <div class="">
            <i class="fa-solid fa-headset text-6xl text-lime-700"></i>
         </div>   
        <p class="text-md text-lime-600">
            24/7 Support
        </p>
        
      
    </div>
</div>
<div class="bg-gray-100 md:pb-28 pb-14">
    <h1 class="text-4xl text-center text-gray-700 font-semibold py-6 uppercase">Deals of the Day</h1>
<div class="md:px-6 px-5 grid md:grid-cols-5 gap-4 grid-cols-1 ">
    {% for product in products %}
<div class="shadow-2xl rounded-b-xl my-4 ">
    <a href="{{product.get_absolute_url}}" class="">
        <img src="{{product.image.url}}" alt="{{product.name}}" class="w-full  h-64 object-center object-cover rounded-t-lg">
        <div class="bg-white rounded-xl p-4 font-sans">
           
                <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">{{product.category}}</h3>
                <h2 class="text-gray-900 title-font text-sm font-medium">{{product.name |title}}</h2>
                <p class="mt-1 "><span class="font-semibold">Price:</span> ${{product.price}}</p>
              
            <div class="mt-2">
                
                    <form action="{% url 'cart:cart_add' product.id %}" method="post" class="">
                        {% csrf_token %}
                        {{form}}
                        <button type="submit" class=" w-full text-white py-2 px-4 rounded text-sm  hover:translate-x-2 hover:duration-700  hover:ease-linear transition-all bg-teal-500 hover:bg-teal-800 hover:text-white uppercase">add to cart</button>
                    </button>
                    </form>
                
            </div>
        </div>
    </a>


</div>
{% endfor %}
</div>
</div>
<div class="min-h-[600px] md:px-2 px-4 py-4 md:py-10 bg-gradient-to-b from-lime-500 to-lime-100">
    
    <h2 class="text-4xl text-center text-white capitalize font-semibold mt-6">
         client reviews
    </h2>
    <hr class="mx-auto w-[120px] mt-3 border-2 border-gray-100 rounded-xl ">
    <div class="my-10 flex justify-between items-center md:space-x-6  flex-col-reverse md:flex-row">
        <div class="mb-4 px-6 py-6 bg-white rounded-xl shadow-2xl">
                <div class="flex items-center justify-between">
                        <div class="">
                        <img src="{% static 'image/client1.png' %}" alt="" class="w-[80px] h-[80px] rounded-full ring-2 ring-lime-300 mr-2" />
                        </div>
                        <div class="">
                        <h2 class=" md:text-lg text-md mb-2 text-gray-700">jane doe</h2>
                    <div class="flex items-center gap-1">
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star-half-stroke text-lime-600"></i>

                    
                            </div>
                        </div>
                    <span class="ml-10">
                        <i class="fa-solid fa-quote-right text-lime-700 text-8xl"></i>
                       
                    </span>
                 </div>
                <div class="mt-2">
                     <p class="text-md leading-tight font-light text-gray-400">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus sit maxime cumque. Exercitationem nisi necessitatibus porro facilis iusto, officiis in.
                     </p>
                </div>
      </div>
        <div class="mb-4 px-6 py-6 bg-white rounded-xl shadow-2xl">
                <div class="flex items-center justify-between">
                        <div class="">
                        <img src="{% static 'image/client2.png' %}" alt="" class="w-[80px] h-[80px] rounded-full ring-2 ring-lime-300 mr-2" />
                        </div>
                        <div class="">
                        <h2 class=" md:text-lg text-md mb-2 text-gray-700">john doe</h2>
                    <div class="flex items-center gap-1">
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star-half-stroke text-lime-600"></i>

                    
                            </div>
                        </div>
                    <span class="ml-10">
                        <i class="fa-solid fa-quote-right text-lime-700 text-8xl"></i>
                    </span>
                 </div>
                <div class="mt-2">
                     <p class="text-md leading-tight font-light text-gray-400">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus sit maxime cumque. Exercitationem nisi necessitatibus porro facilis iusto, officiis in.
                     </p>
                </div>
      </div>
        <div class="mb-4 px-6 py-6 bg-white rounded-xl shadow-2xl">
                <div class="flex items-center justify-between">
                        <div class="">
                        <img src="{% static 'image/client3.png' %}" alt="" class="w-[80px] h-[80px] rounded-full ring-2 ring-lime-300 mr-2" />
                        </div>
                        <div class="">
                        <h2 class=" md:text-lg text-md mb-2 text-gray-700">lindah smith</h2>
                    <div class="flex items-center gap-1">
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star text-lime-600"></i>
                        <i class="fa-solid fa-star-half-stroke text-lime-600"></i>

                    
                            </div>
                        </div>
                    <span class="ml-10">
                        <i class="fa-solid fa-quote-right text-lime-700 text-8xl"></i>
                    </span>
                 </div>
                <div class="mt-2">
                     <p class="text-md leading-tight font-light text-gray-400">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus sit maxime cumque. Exercitationem nisi necessitatibus porro facilis iusto, officiis in.
                     </p>
                </div>
      </div>
      
     
</div>
    </div>
</div>
<script>
  $('.single-item-rtl').slick({
  rtl: true
});
	
</script>
{% endblock %}

templates/product/product_detail.html
{% extends 'base.html' %}

{% block title %}
{{product.name}}
{% endblock %}
{% block content %}
<style>
    /* Styles for the modal (full-screen overlay) */
    .modal {
        display: none;
        position: fixed;
        z-index: 9999;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.9);
    }

    /* Styles for the modal content (enlarged image) */
    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 800px;
        margin-top: 10%;
    }

    /* Close button for the modal */
    .close {
        position: absolute;
        top: 30px;
        right: 30px;
        color: #fff;
        font-size: 40px;
        font-weight: bold;
        cursor: pointer;
    }
    @media screen and (max-width: 600px) {
        .modal-content {
            width: 90%;
            margin-top: 30%;
        }
        .close {
            top: 10px;
            right: 10px;
            font-size: 30px;
        }
    }
</style>
<section class="max-w-6xl py-10 mx-auto bg-lime-50">
   <div class="mx-6">
    <a href="{% url 'product:landing' %}" class="rounded-full bg-sky-500 hover:bg-cyan-800 duration-300 inline-flex items-center justify-center px-1.5 py-1">
        <i class="text-3xl text-white fa-solid fa-arrow-left "></i>
        
        </a>
   </div>
    <div class="grid justify-center px-4 py-4 md:grid-cols-3 md:gap-10 place-content-center">
        <div class="mb-6 md:col-span-2">
            <img src="{{product.image.url}}" alt="" class="shadow-2xl rounded-xl h-[600px] w-full object-center object-cover" id="mainImage">
            {% if product.image_1 or product.image_2 or product.image_3 %}
            <div class="flex flex-row flex-wrap items-center justify-center mt-10">
                
                {% if product.image_1 %}
                    <img src="{{ product.image_1.url }}" alt="" class="object-cover object-center w-16 h-16 mx-4 md:w-32 md:h-32 rounded-xl" onclick="setMainImage('{{ product.image_1.url }}')">
                {% endif %}
                
                {% if product.image_2 %}
                    <img src="{{ product.image_2.url }}" alt="" class="object-cover object-center w-16 h-16 mx-4 md:w-32 md:h-32 rounded-xl" onclick="setMainImage('{{ product.image_2.url }}')">
                {% endif %}
                
                {% if product.image_3 %}
                    <img src="{{ product.image_3.url }}" alt="" class="object-cover object-center w-16 h-16 mx-4 md:w-32 md:h-32 rounded-xl" onclick="setMainImage('{{ product.image_3.url }}')">
                {% endif %}
                <img src="{{product.image.url}}" alt="" class="object-cover object-center w-16 h-16 mx-4 md:w-32 md:h-32 rounded-xl" onclick="setMainImage('{{ product.image.url }}')">
            </div>
        {% endif %}     
        </div>
        <div class="md:col-span-1 ">
            <div class="p-4 text-white bg-gradient-to-b from from-blue-500 to-blue-900 rounded-xl">
                <h2 class="mb-3 text-2xl font-extrabold text-center capitalize md:text-start">
                    {{product.name}}
                </h2>
                <p class="mb-2 text-xl">Category: <span class="font-bold text-center"><a href="" class="">{{product.category}}</a></span></p>
                <p class="mt-6 text-xl">Size: <span class="px-2 py-2 text-white bg-teal-500 rounded-full ">{{product.size}}</span><span class="text-rose-500"> {{product.available_size}}</span></p>
                <p class="mt-6 text-xl">Price: <span class="font-bold">${{product.price}}</span></p>
                {% comment %}
                {% if product.description %}
                    <p class="mb-8 text-xl line-clamp-3">Description: <span class="block text-sm font-light ">{{ product.description }}</span></p>
                {% endif %}
            {% endcomment %}
                <div class="mx-4 my-8">
                    <form action="{% url 'cart:cart_add' product.id %}" method="post" class="flex items-center justify-around">
                        {% csrf_token %}
                        {{form}}
                        <input type="submit" value="add to cart" class="w-full px-4 py-4 text-lg capitalize bg-teal-500 hover:bg-teal-700">
                    
                    </form>
                    <script>
                        $(document).ready(function () {
                            $("#add-to-cart-button").on("click", function () {
                                $("input[name='add_to_cart']").val(true);
                                $("form").submit();
                            });
                        });
                    </script>
                </div>
            </div>
            
    </div>
    
    </div>
    {% comment %}  
 <div class="px-4 py-4 md:px-12 md:py-6">
    {% if related_products %}
    <h2 class="mb-6 font-mono text-4xl font-bold text-center text-gray-800 capitalize">related art</h2>
    <div class="grid grid-cols-1 gap-4 md:grid-cols-3 place-content-center">
        {% for product in related_products %}
        <div class="shadow-2xl">
          <img src="{{product.image.url}}" alt="{{product.name}}" class="object-cover object-center w-full h-64 rounded-t-lg md:h-80">
          <a href="{{product.get_absolute_url}}" class="">
            <div class="px-4 py-6 bg-white rounded-b-xl">
                <p class="text-2xl font-semibold mb">{{product.name}}</p>
                <p class="text-xl">Price: $<strong>{{product.price}}</strong></p>
            </div>
        </a>
        </div>
        
        {% endfor %}
    </div>
    {% else  %}
        <h2 class="my-4 text-6xl text-center">No related arts to this Item</h2>
     {% endif %}   

 </div>
 {% endcomment %}
 <!-- Modal for zoomed image -->
<div id="zoomModal" class="modal">
    <span class="close" onclick="closeModal()">&times;</span>
    <img class="modal-content" id="zoomedImage">
</div>
</section>
<script>
    function setMainImage(imageUrl) {
        document.getElementById('mainImage').src = imageUrl;
    }
    
    function openModal() {
        document.getElementById('zoomModal').style.display = 'block';
        document.getElementById('zoomedImage').src = document.getElementById('mainImage').src;
    }

    function closeModal() {
        document.getElementById('zoomModal').style.display = 'none';
    }

    
    document.getElementById('mainImage').addEventListener('click', openModal);
</script>
{% endblock %}

templates/product/product_list.html
{% extends 'base.html' %}

{% block  title %}
{% if category %}{{category.name}} {% else %}Products{%endif %}
{% endblock %}
{% block content %}
<div class="max-w-7xl mx-auto grid md:grid-cols-4 gap-4 grid-cols-1  font-sans my-10">
<div class="col-span-1 md:block hidden ">
  <ul class="space-y-4 py-10 px-10 w-full bg-gray-100 shadow-2xl">
    <h3 class="text-2xl text-center mb-6">Categories</h3>
      <li class="px-6 py-3 rounded-xl text-center {% if not category %} bg-gray-300 {% endif %}">
          <a href="{% url 'product:product_list' %}" class="  ">All</a>
      </li>
       {% for c in categories %}
       <li class="px-6 py-3 rounded-xl  text-center {% if category.slug == c.slug %}bg-gray-700 text-white{% endif %}">
          <a href="{{c.get_absolute_url}}" class="">{{c.name}}</a>
       </li>
       {% endfor %}
       <a href="{% url 'product:product_list' %}" class="bg-rose-500 text-lg inline-flex justify-center items-center text-white px-6 w-full text-center mt-2 py-4 rounded-xl">clear</a>
  </ul>
 
</div>
<div class="md:col-span-3 col-span-1">
  <h1 class="text-4xl text-center text-gray-800 font-semibold font-sans">{% if category %}{{category.name}} {% else %}Products{%endif %}</h1>
<section class="text-gray-600 font-sans">
  <div class="container">
    <div class="flex flex-wrap ">
      {% for product in products %}
      <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
        <a href="{{product.get_absolute_url}}" class="block relative h-48 rounded overflow-hidden">
          <img alt="{{product.name}}" class="object-cover object-center w-full h-full block" src="{{product.image.url}}">
        </a>
        <div class="mt-4">
          <h3 class="text-gray-500 text-xs tracking-widest title-font mb-1">{{product.category}}</h3>
          <h2 class="text-gray-900 title-font text-lg font-medium">{{product.name |title}}</h2>
          <p class="mt-1">${{product.price}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
</div>
</div>
{% endblock %}