art_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('product.urls', namespace='product')),
     path("__reload__/", include("django_browser_reload.urls")),
   
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from .views import (cart_add,cart_detail,cart_remove)

app_name='cart'

urlpatterns=[
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    
]

templates/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>{% block title %}{% endblock %} | Shop</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="">
        
		<header class="bg-gradient-to-b from-cyan-600 to-blue-400 drop-shadow-2xl">
			<nav class="flex items-center justify-between mx-2 md:mx-14">
				<div class="py-2">
					<a href="/">
						<img src="{% static 'image/logo.png' %}" alt="logo" class="w-3/5 bg-white rounded ">
					</a>
				</div>
				<div class="items-center justify-center hidden space-x-8 text-xl font-extralight md:flex">
					<a href="" class="relative text-white capitalize group">
						home
						<span class="duration-300 absolute bottom-0 inset-x-0 scale-x-0 transform transition-transform origin-left bg-white group-hover:scale-x-100 h-0.5 "></span>
					</a>
					<a href="" class="relative text-white capitalize group">
						about
						<span class="duration-300 absolute bottom-0 inset-x-0 scale-x-0 transform transition-transform origin-left bg-white group-hover:scale-x-100 h-0.5 "></span>

					</a>
					<a href="" class="relative text-white capitalize group">
						contact
						<span class="duration-300 absolute bottom-0 inset-x-0 scale-x-0 transform transition-transform origin-left bg-white group-hover:scale-x-100 h-0.5 "></span>
										</a>
					{% with total_items=cart|length %}
					{% if total_items > 0 %}
						<a href="{% url 'cart:cart_detail' %}" class="relative">
							<span class="absolute top-0 right-0 inline-flex items-center justify-center px-2 py-1 text-xs font-bold leading-none text-gray-800 transform translate-x-1/2 -translate-y-1/2 bg-white rounded-full" id="cart-count">{{total_items}}</span> 
							<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" data-slot="icon" class="w-6 h-6 text-white cursor-pointer">
								<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007ZM8.625 10.5a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Zm7.5 0a.375.375 0 1 1-.75 0 .375.375 0 0 1 .75 0Z" />
							  </svg>						  
							  
						</a>
					{% elif not order %}
					<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-white cursor-pointer">
						<path stroke-linecap="round" stroke-linejoin="round" d="M15.75 10.5V6a3.75 3.75 0 10-7.5 0v4.5m11.356-1.993l1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 01-1.12-1.243l1.264-12A1.125 1.125 0 015.513 7.5h12.974c.576 0 1.059.435 1.119 1.007zM8.625 10.5a.375.375 0 11-.75 0 .375.375 0 01.75 0zm7.5 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
					  </svg> 
					{% endif %} 
					{% endwith %}

				</div>
				
				
			</nav>
		</header>

	
		

		
		{% block content%}
		<div class="">
			
		</div>
		{% endblock %}
	
<footer class="bg-gradient-to-br from-sky-700 to-blue-800 min-h-400px">
	<div class="px-4 py-6 md:px-10">
		<div class="flex flex-col items-center justify-between md:flex-row ">
			<div class="w-full mb-4 md:w-2/5">
				<img src="{% static 'image/logo.png' %}" alt="logo" class="bg-white rounded md:mb-4">
				<p class="text-white font-extralight">
					The <strong>revived artist</strong> group was founded in 2019 with a vision to create a platform for emerging and established artists to showcase their talents and connect with art enthusiasts worldwide. This group aims to revive and promote various forms of art, including visual arts, music, literature, performing arts, and more.
				</p>
			</div>
			<div class="flex flex-col justify-around w-full md:w-3/4 md:flex-row ">
                <div class="mb-4">
					<h2 class="mb-4 text-2xl font-semibold text-white capitalize">
						useful links
					</h2>
					<div class="flex flex-col space-y-2.5">
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">home</a>
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">about</a>
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">contact</a>
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">privacy policy</a>
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">terms of use</a>

					</div>
				</div>
				<div class="">
					<h2 class="mb-4 text-2xl font-semibold text-white capitalize">
						location
					</h2>
					<div class="">
						<div class="flex items-center mb-2 space-x-4">
							<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">
								<i class="text-2xl fa-sharp fa-solid fa-location-dot"></i>
							</a>
							<p class="text-white text-md">
							 Nairobi, Kimathi street
							</p>

						</div>
						<div class="flex items-center mb-2 space-x-4">
							<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">
								<i class="text-2xl fa-solid fa-phone"></i>
							</a>
							<p class="text-white text-md">
							  +254 712-345-62
							</p>

						</div>
						<div class="flex items-center mb-2 space-x-4">
							<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">
								<i class="text-2xl fa-solid fa-envelope"></i>
							</a>
							<p class="text-white text-md">
								revivedartist@hello.com
							</p>

						</div>
					</div>
					<div class="flex items-center mt-6 space-x-6 md:justify-center">
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">
							<i class="text-2xl fa-brands fa-facebook"></i>
						</a>
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">
							<i class="text-2xl fa-brands fa-twitter"></i>
						</a>
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">
							<i class="text-2xl fa-brands fa-instagram"></i>
						</a>
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">
							<i class="text-2xl fa-brands fa-youtube"></i>
						</a>
						<a href="" class="font-light capitalize transition-transform duration-300 delay-100 text-md text-gray-50 hover:translate-x-2">
							<i class="text-2xl fa-brands fa-pinterest"></i>
						</a>
						
						
						

					</div>
				</div>
			</div>
		</div>
		<p class="mt-4 font-light text-center text-white">
			Copyright  &copy; revivedartist  {% now "Y" %}
		</p>
	</div>
</footer>
<script src="https://kit.fontawesome.com/a0e99f8a3c.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
	</body>
</html>