art_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/',include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('product.urls', namespace='product')),
     path("__reload__/", include("django_browser_reload.urls")),
   
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from .views import (cart_add,cart_detail,cart_remove)

app_name='cart'

urlpatterns=[
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    
]

payment/urls.py
from django.urls import path
from .views import (payment_process,payment_completed,payment_canceled)
from . import webhooks
app_name='payment'

urlpatterns=[
    path('process/', payment_process, name='process'),
    path('completed/', payment_completed, name='completed'),
    path('canceled/', payment_canceled, name='canceled'),
    path('webhook/', webhooks.stripe_webhook, name='stripe-webhook'),
]

product/urls.py
from django.urls import path
from .views import (product_list, product_detail,landing_page)

app_name='product'

urlpatterns=[
    path('',landing_page, name='landing' ),
    path('list/',product_list, name='product_list'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('detail/<int:id>/<slug:slug>/', product_detail, name='product_detail'),
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render, redirect,get_object_or_404
from  django.urls import reverse
import stripe
from django.conf import settings
from orders.models import Order
from decimal import Decimal
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from . import webhooks

"Stripe API instance"
stripe.api_key=settings.STRIPE_SECRET_KEY
stripe.api_version=settings.STRIPE_API_VERSION

def payment_process(request):
    order_id=request.session.get('order_id',None)
    order=get_object_or_404(Order, id=order_id)

    if request.method =='POST':
        success_url=request.build_absolute_uri(reverse('payment:completed'))
        cancel_url=request.build_absolute_uri(reverse('payment:canceled'))

        #Stripe checkout session data
        session_data={
            'mode':'payment',
            'client_reference_id':order.id,
            'success_url':success_url,
            'cancel_url':cancel_url,
            'line_items':[]
        }
        #add order items to Stripe checkout session
        for item in order.items.all():
            session_data['line_items'].append({
                'price_data':{
                    'unit_amount':int(item.price * Decimal('100')),
                    'currency':'usd',
                    'product_data':{
                        'name':item.product.name,
                    },
                },
                'quantity':item.quantity,
            })

        #Stripe Checkout session
        session=stripe.checkout.Session.create(**session_data)
        #redirect to Stripe payment form
        return redirect(session.url, code=303)
    else:
        return render(request, 'payment/process.html',locals())
    
def payment_completed(request):
    return render(request,'payment/completed.html')


def payment_canceled(request):
    return render(request,'payment/canceled.html')


""""
@csrf_exempt
def stripe_webhook(request):
    payload=request.body
    sig_header=request.META['HTTP_STRIPE_SIGNATURE']
    event=None

    try:
        event=stripe.Webhook.construct_event(
            payload,
            sig_header,
            settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        #Invalid Payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        #Invalid signature

        return HttpResponse(status=400)
        
    if event.type == 'checkout.session.completed':
        session=event.data.object

        if session.mode =='payment' and session.payment_status == 'paid':
            try:
                order=Order.objects.get(id=session.client_reference_id)
            except Order.DoesNotExist:
                return HttpResponse(status=404)
            #mark the order as paid
            order.paid=True
            #store Stripe payment ID
            order.stripe_id=session.payment_intent
            order.save()
            #launch asynchronous task
            payment_completed.delay(order.id)
    
    return HttpResponse(status=200)

"""

            

templates/payment/canceled.html
{% extends 'base.html' %}

{% block title %}
Payment Canceled
{% endblock %}

{% block content %}
<div class="bg-gradient-to-bl from-lime-800 py-20 px-10 md:px-0 to-lime-700 min-h-[400px]">
    <div class="max-w-xl py-20  rounded-xl bg-white mx-auto shadow-2xl">
           <span class="flex justify-center items-center ">
            <i class="fa-solid fa-money-bill-1 text-7xl text-white bg-lime-400 rounded-full px-6 py-6"></i>
           </span>
        <h2 class="md:text-4xl text-xl text-center capitalize text-gray-700">
            Your payment has not been processed
        </h2>
        <p class="text-lime-700 mt-6 text-center md:text-base text-sm">There was a problem processing your payment .</p>

    </div>
</div>

{% endblock %}

templates/payment/completed.html
{% extends 'base.html' %}
{% block title %}
Payment successful
{% endblock %}

{% block content %}
<div class="bg-gradient-to-bl from-lime-800 py-20 px-10 md:px-0 to-lime-700 min-h-[400px]">
    <div class="max-w-md py-20  rounded-xl bg-white mx-auto shadow-2xl">
        <div class="flex justify-center">
            <i class="fa-solid fa-money-bill-wave text-7xl text-white bg-lime-400 rounded-full px-6 py-6"></i>

        </div>
        <h1 class="md:text-4xl text-xl text-center">
            Your payment was successfull 😊
        </h1>
        <p class="text-md text-center mt-8 text-gray-700">
            Thank you for shopping.Please check your email
            for receipt with your order details  
        </p>
        <div class="my-10">
            <p class="text-lg text-center font-semibold">
                view more 
                <a href="{% url 'product:landing' %}" class="text-lime-500 underline underline-offset-4">
                    art drawing 🎨
                </a>
            </p>
        </div>
    </div>
    
</div>
{% endblock %}

templates/payment/process.html
{% extends 'base.html' %}

{% block title %}
Pay your order
{% endblock %}

{% block content %}

<div class="">
    <div class="max-w-md mx-10 my-20 shadow-2xl md:mx-auto rounded-2xl bg-gradient-to-bl from-sky-800 to-sky-700">
            
        <div class="px-4 py-2 ">
            <h2 class="font-sans text-3xl font-semibold text-center text-white">Your Shopping Cart</h2>
        </div>
        <div class="divide-y divide-gray-200 ">
            {% for item in order.items.all %}
            <div class="flex items-center justify-between px-6 py-4">
                <a href="{{product.get_absolute_url}}" class="">
                    <img class="object-cover w-16 h-16 rounded" src="{{item.product.image.url}}" alt="Product Image">
                </a>
                <div class="ml-3">
                    <h3 class="font-sans font-semibold text-white ">{{item.product.name}}</h3>
                    <p class="mt-2 font-sans font-semibold text-white text-end">$ {{item.price}}</p>
                </div>
               
        
          
            </div>
            {% endfor %}
            <h3 class="p-4 font-sans text-3xl text-white text-end">Total: <span class="mx-2 font-semibold">${{order.get_total_cost}}</span></h3>
            
            <div class="flex items-center justify-center px-6 py-3 font-sans">
                <form action="{% url 'payment:process' %}" method="post">
                    <input type="submit" value="Pay now" class="px-10 py-6 text-xl text-white bg-teal-500 cursor-pointer rounded-xl">
                    {% csrf_token %}
                </form>
        </div>
    
            
            </div>
    </div>

</div>
{% endblock %}